#! /bin/sh

sxhkd &
feh --bg-fill ~/ピクチャ/緑/1.jpg &
$HOME/.config/bspwm/polybar/launch.sh

# bspc monitor -d I II III IV V VI VII VIII IX X

# multi monitor rules
# get monitor name from: xrandr -q | grep -w connected
bspc monitor DP-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
